Assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AssignmentApp.urls', namespace='AssignmentApp',))

]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

AssignmentApp/urls.py

from django.urls import path
from . import views

app_name = 'AssignmentApp'

urlpatterns = [
    path('', views.index, name='index_temp'),
    path('course-vedios/<int:pk>/', views.allcoursevedios, name="course_vedios_temp"),

]

AssignmentApp/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
	"""docstring for Course"""
	title = models.CharField(max_length=30, blank=True, help_text="Provide course title.", verbose_name="Title")
	description = models.TextField(help_text="Provide course description.", verbose_name="Description")
	course_image = models.FileField(upload_to='course/images', null=True, help_text="upload course vedio.", verbose_name="Course Image")
	
	def __str__(self):
		return str(self.title)

	class Meta:
		verbose_name = "Course"
		verbose_name_plural = "Courses"


# Create your models here.
class CourseVideos(models.Model):
	"""docstring for Course"""
	Course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="course_videos")
	vediofile = models.FileField(upload_to='course/videos', null=True, help_text="upload course vedio.", verbose_name="Vedio File")

	class Meta:
		verbose_name = "Course Video"
		verbose_name_plural = "Course Videos"

AssignmentApp/views.py
from django.shortcuts import render
from .models import Course, CourseVideos

# Create your views here.
def index(request):
	course_obj = Course.objects.all()
	return render(request, 'index.html', {"course_obj":course_obj})


def allcoursevedios(request, pk):
	course_videos = CourseVideos.objects.filter(Course_id=pk)
	return render(request, 'all_course_vedios.html', {"course_videos_obj":course_videos})
	

templates/all_course_vedios.html
{% extends 'base.html' %}
{% block heading %}
<h1>Course Vedios Content</h1>
{% endblock %}
{% block back %}
<a href="/" class="btn btn-primary my-2">Back</a>
{% endblock %}
}
{% block content %}
<div class="album py-5 bg-light">
   <div class="container">
      {% if not course_videos_obj %}
      <h4>Course Doesn't have any vedio.</h4>
      {% endif %}
      <div class="row">
         {% for obj in course_videos_obj %}
         <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
               <video width='100%' height="225" class="bd-placeholder-img card-img-top" controls>
                  <source src="{{ obj.vediofile.url }}" type='video/mp4' class="card-img-top">
                  Your browser does not support the video tag.
               </video>
               <div class="card-body">
                  <p class="card-text">{{obj.Course.title}}</p>
                  <p class="card-text">{{obj.Course.description|truncatewords:30}}</p>
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <title>Home</title>
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <a class="navbar-brand" href="/">Home</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
      </nav>
      <main role="main">
         <section class="jumbotron text-center">
            <div class="container">
               {% block heading %}
               {% endblock %}
               <p>
                  {% block back %}
                  {% endblock %}
               </p>
            </div>
         </section>
         {% block content %}
         {% endblock %}
      </main>
      <footer class="text-muted">
         <div class="container">
            <p class="float-right">
               <a href="#" class="btn btn-primary my-2">Back to top</a>
            </p>
         </div>
      </footer>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
   </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block heading %}
<h1><b>Welcome to the Learning Portal</b></h1>
{% endblock %}
{% block content %}
<div class="album py-5 bg-light">
   <div class="container">
      <div class="row">
         {% for obj in course_obj %}
         <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
               <img src="{{obj.course_image.url}}" width='100%' height="225" class="bd-placeholder-img card-img-top">
               <div class="card-body">
                  <p class="card-text">{{obj.title}}</p>
                  <p class="card-text">{{obj.description|truncatewords:30}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                     <div class="btn-group">
                        <a href="{% url 'AssignmentApp:course_vedios_temp' obj.id %}" type="button" class="btn btn-sm btn-outline-secondary">View All</a>
                     </div>
                     <small class="text-muted">9 mins</small>
                  </div>
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
</div>
{% endblock %}